use_frameworks!

target 'DelGate' do
  pod 'SwiftyJSON', '3.1.4'      # 4.0.0
  pod 'Charts', '3.0.3'
  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'

  # See http://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

  # react-native-maps dependencies
  pod 'react-native-maps', path: rn_maps_path
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'
  pod 'Firebase/Messaging'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'    # 4.0
    end
  end
end